version: 0.2

env:
  variables:
    BROWSER: "phantomjs"
    WebURL: "https://sampletestweb.s3-eu-west-1.amazonaws.com/website/index.html"
    ArtifactBucket: "codebuild-demo-artifact-repository"
    MODULES: "mod1"
    ModuleTable: "test-modules"
    StatusTable: "blog-test-status"
    LambdaRole: "arn:aws:iam::account-id:role/role-name"

phases:
  install:
    commands:
      - apt-get update
      - apt-get -y upgrade
      - apt-get install python python-pip build-essential -y
      - apt-get install -y chrpath libssl-dev libxft-dev
      - apt-get install -y libfreetype6 libfreetype6-dev
      - apt-get install -y libfontconfig1 libfontconfig1-dev
      - apt-get install zip unzip -y
      - apt-get install mlocate -y
      - pip install --upgrade pip
      - pip install selenium
      - pip install awscli
      - pip install requests
      - pip install boto3
      - updatedb
  build:
    commands:
      - cd ~
      - wget -N http://chromedriver.storage.googleapis.com/2.26/chromedriver_linux64.zip
      - unzip chromedriver_linux64.zip
      - chmod +x chromedriver
      - mv -f chromedriver /usr/local/share/chromedriver
      - ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
      - ln -s /usr/local/share/chromedriver /usr/bin/chromedriver
      - which chromedriver
      - python /codebuild/readonly/src/check_ct_test
#      - export PHANTOM_JS="phantomjs-1.9.8-linux-x86_64"
#      - wget https://bitbucket.org/ariya/phantomjs/downloads/$PHANTOM_JS.tar.bz2
#      - tar xvjf $PHANTOM_JS.tar.bz2
#      - mv $PHANTOM_JS /usr/local/share
#      - ln -sf /usr/local/share/$PHANTOM_JS/bin/phantomjs /usr/local/bin
#      - func_name=`echo $CODEBUILD_BUILD_ID | awk -F ':' '{print $1}'`-phantomjs
#      - export PhantomJSFunction=$func_name
#      - which phantomjs
